services:
  backend:
    image: siddheshkaremore/cinema-paglu-backend:latest
    container_name: cinema-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    image: siddheshkaremore/cinema-paglu-frontend:latest
    container_name: cinema-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped