spring.application.name=cinema

# DB Connection for postgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# 86400000ms = 24 hours

logging.level.org.springframework=INFO
logging.level.com.project.cinema=DEBUG

# Show all endpoints including ones needing auth
springdoc.show-actuator=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
